//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestSellingProducts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExamDBEntities : DbContext
    {
        public ExamDBEntities()
            : base("name=ExamDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<GetTopFiveEveryCategory_Result> GetTopFiveEveryCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopFiveEveryCategory_Result>("GetTopFiveEveryCategory");
        }
    
        public virtual ObjectResult<GetTopTen_Result> GetTopTen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopTen_Result>("GetTopTen");
        }
    }
}
