//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestSellingProducts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
